# Generated by Django 5.2.2 on 2025-06-06 21:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=10, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BankAccount',
                'indexes': [models.Index(fields=['balance'], name='BankAccount_balance_ac03a9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0.0)), name='check_balance')],
            },
        ),
    ]
